---

- name: copying kafka service script
  template:
    src: "kafka.service.j2"
    dest: /etc/systemd/system/kafka.service
    owner: kafka
    group: confluent
    mode: '0644'

- name: set Telegraf Jolokia config 
  template:
    src: "jolokia-kafka.conf.j2"
    dest: /etc/telegraf/telegraf.d/jolokia-kafka.conf
    mode: '0755'

- name: set Telegraf config 
  template:
    src: "telegraf.conf.j2"
    dest: /etc/telegraf/telegraf.conf
    mode: '0755'

- name: set Kafka broker config 
  template:
    src: "server.properties.j2"
    dest: /etc/kafka/server.properties
    mode: '0755'

- name: copy awslogs conf
  copy:
    src: awslogs.conf
    dest: "/etc/awslogs/awslogs.conf"
    mode: 0644

- name: enable service
  systemd:
      enabled: yes
      name: "{{ item.name }}"
  with_items:
    - { name: 'kafka' }
    
    