---
- name: copy InfluxDB repo
  copy:
    src: influxdb.repo
    dest: "/etc/yum.repos.d/influxdb.repo"
    mode: 0644

- name: install Telegraf agent
  yum:
    name: "telegraf"
    state: latest

- name: copy Telegraf conf
  template:
    src: telegraf.conf.j2
    dest: "/etc/telegraf/telegraf.conf"
    mode: 0644

